### ISSUE TITLE
md5 checksum error for metaphlan database

### ISSUE THREAD

**Issue by zer0liu** [biobakery/MetaPhlAn#100]
Thank you for release MetaPhlAn 3.

When i tried to download the database, i encountered the error "MD5 checksums do not correspond!".

The complete message was:

> $ metaphlan --install 
> Warning! Biom python library not detected!
>  Exporting to biom format will not work!
> 
> Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
> Downloading file of size: 0.00 MB
> 0.01 MB 232.33 %   4.52 MB/sec  0 min -0 sec         
> Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAAyoJpOgcjop41VIHAGWIVLa/mpa_latest?dl=1
> Downloading file of size: 0.00 MB
> 0.01 MB 31507.69 %   4.27 MB/sec  0 min -0 sec         
> Downloading MetaPhlAn database
> Please note due to the size this might take a few minutes
> 
> File /home/gweaver/miniconda3/envs/mpa3/lib/python3.8/site-packages/metaphlan/metaphlan_databases/file_list.txt already present!
> 
> Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AADlxibskzbPHPoDl6S-FyKka/mpa_v30_CHOCOPhlAn_201901.tar?dl=1
> Downloading file of size: 366.71 MB
> 366.70 MB 100.00 %   2.36 MB/sec  0 min  0 sec         
> Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AADlxibskzbPHPoDl6S-FyKka/mpa_v30_CHOCOPhlAn_201901.tar?dl=1
> 
> Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AACTzoUYDqZps8u2JqWCNCODa/mpa_v30_CHOCOPhlAn_201901.md5?dl=1
> Downloading file of size: 0.00 MB
> MD5 checksums do not correspond! If this happens again, you should remove the database files and rerun MetaPhlAn so they are re-downloaded
> 

This also happened for database v296 with the command:
> $ metaphlan --install --index mpa_v296_CHOCOPhlAn_201901

How to resolve this error? Thanks a lot!

**Comment by fbeghini** [comment]
Can you access to dropbox from your web browser?

**Comment by zer0liu** [comment]
I re-installed MetaPhlAn 3 by pip and the problem resolved.
Thank you!
