### ISSUE TITLE
[Warnings] MetaPhlAn version 3.0

### ISSUE THREAD

**Issue by ShaBioinformer** [biobakery/MetaPhlAn#101]
I have installed **MetaPhlAn version 3.0** (20 Mar 2020) using
`conda create --name mpa -c bioconda metaphlan`
and downloaded and built the database without problem. Here is the list of files created in **metaphlan_databases** folder.

- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/file_list.txt
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_latest
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.1.bt2
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.2.bt2
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.3.bt2
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.4.bt2
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.fna.bz2
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.md5
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.pkl
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.rev.1.bt2
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.rev.2.bt2
- envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.tar

But, when I do `metaphlan test.fastq --input_type fastq -o test.txt` a wrong result file will be created:

> #mpa_v30_CHOCOPhlAn_201901
> #/envs/mpa/bin/metaphlan test.fastq --input_type fastq -o test.txt
> #SampleID	Metaphlan_Analysis
> #clade_name	NCBI_tax_id	relative_abundance	additional_species
> UNKNOWN	-1	100.0

and I receive these errors on the command prompt:

> Use of uninitialized value $bt2_args[2] in join or string at /envs/mpa/bin/bowtie2 line 423.
> Use of uninitialized value $bt2_args[3] in join or string at /envs/mpa/bin/bowtie2 line 423.
> Use of uninitialized value $_[2] in string eq at /envs/mpa/bin/bowtie2 line 360.
> Use of uninitialized value $_[3] in string eq at /envs/mpa/bin/bowtie2 line 360.
> Use of uninitialized value in exists at /envs/mpa/bin/bowtie2 line 81.
> Use of uninitialized value in exists at /envs/mpa/bin/bowtie2 line 81.
> Use of uninitialized value $bt2_args[2] in join or string at /envs/mpa/bin/bowtie2 line 459.
> Use of uninitialized value $bt2_args[3] in join or string at /envs/mpa/bin/bowtie2 line 459.

I have this problem both on Linux and MacOS.
Thanks.

**Comment by fbeghini** [comment]
>UNKNOWN -1 100.0
Which kind of metagenome are you trying to profile with MetaPhlAn? Is the bowtie2out file empty?

>Use of uninitialized value $bt2_args[2] in join or string at /envs/mpa/bin/bowtie2 line 423.
>Use of uninitialized value $bt2_args[3] in join or string at /envs/mpa/bin/bowtie2 line 423.
>Use of uninitialized value $[2] in string eq at /envs/mpa/bin/bowtie2 line 360.
>Use of uninitialized value $[3] in string eq at /envs/mpa/bin/bowtie2 line 360.
>Use of uninitialized value in exists at /envs/mpa/bin/bowtie2 line 81.
>Use of uninitialized value in exists at /envs/mpa/bin/bowtie2 line 81.
>Use of uninitialized value $bt2_args[2] in join or string at /envs/mpa/bin/bowtie2 line 459.
>Use of uninitialized value $bt2_args[3] in join or string at /envs/mpa/bin/bowtie2 line 459.

This seems to be a Perl related issue,  can you run and paste here the output of `stat /envs/mpa/bin/bowtie2`?

**Comment by Fedorov113** [comment]
I get bowtie2 related warnings too, everything else works as expected, I am on conda version.

**Comment by ShaBioinformer** [comment]
Thanks for your fast response.
`stat  /envs/mpa/bin/bowtie2` 
```
 File: /envs/mpa/bin/bowtie2
  Size: 21387           Blocks: 48         IO Block: 8192   regular file
Device: 18h/24d Inode: 559441060   Links: 2
Access: (0775/-rwxrwxr-x)  Uid: ( 1099/sbsaghaei)   Gid: ( 1001/    ctgb)
Access: 2020-06-12 11:59:15.842050500 +0200
Modify: 2020-06-06 22:22:08.000000000 +0200
Change: 2020-06-12 11:30:40.286024205 +0200
 Birth: -
```
This is a simulated metagenome containing only two bacteria.
I checked with another fastq and it shows these warnings but the result file seems ok now.
Probably, the test.fastq was too short for metaphlan to find the marker genes.

**Comment by fbeghini** [comment]
The warning messages should not affect the MetaphlAn results, I was not able to reproduce the exact output by installing again MetaPhlAn from conda.  The permissions on the `bowtie2` executable are OK, maybe you should check whether setuid/setgid are set for the `perl` executable.

>Probably, the test.fastq was too short for metaphlan to find the marker genes
MetaPhlAn should work with ~100k reads

**Comment by fbeghini** [comment]
@ShaBioinformer @Fedorov113 Can you check which bowtie2 version are you running?

**Comment by ShaBioinformer** [comment]
Hi @fbeghini, Thanks for following the issue.
In both of Linux and Mac the bowtie version is,
`bowtie2-2.4.1`

Linux:
64-bit
Built on 
Sat Jun  6 20:17:22 UTC 2020Compiler: gcc version 7.5.0 (crosstool-NG 1.24.0.123_1667d2b) 
Options: -O3 -msse2 -funroll-loops -g3 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /conda/metax/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie2_1591474367590/work=/usr/local/src/conda/bowtie2-2.4.1 -fdebug-prefix-map=/conda/metax=/usr/local/src/conda-prefix -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

MacOS:
64-bit
Built on 
Sat Jun  6 20:43:32 UTC 2020
Compiler: InstalledDir: /Users/distiller/project/miniconda/conda-bld/bowtie2_1591476031995/_build_env/bin
Options: -O3 -msse2 -funroll-loops -g3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem /Users/meow/opt/miniconda3/envs/mpa/include -fdebug-prefix-map=/Users/distiller/project/miniconda/conda-bld/bowtie2_1591476031995/work=/usr/local/src/conda/bowtie2-2.4.1 -fdebug-prefix-map=/Users/meow/opt/miniconda3/envs/mpa=/usr/local/src/conda-prefix -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

**Comment by fbeghini** [comment]
By manually checking the BowTie2 command line, it seems that the warning is related to the usage of the `--no-unal` flag. Also, the same warning is reported in a issue in the bowtie2 repo (https://github.com/BenLangmead/bowtie2/issues/293): (TLDR warnings are thrown but the unaligned reads are correctly not reported in the SAM).
It is not affecting the MetaPhlAn output, by all means.
