### ISSUE TITLE
[I] Remove "[default 'FASTQ']" from required --input_type argument

### ISSUE THREAD

**Issue by tvatanen** [biobakery/MetaPhlAn#107]
Why does the --input_type argument have a default 'FASTQ' even though this is a required argument and metaphlan will return an error if this is not given?

Required arguments:
  --input_type {fastq,fasta,bowtie2out,sam}
                        set whether the input is the FASTA file of metagenomic reads or
                        the SAM file of the mapping of the reads against the MetaPhlAn db.
                        [default 'FASTQ']

**Comment by fbeghini** [comment]
Makes sense, I'll remove the default value and make it required.
