### ISSUE TITLE
[BUG] using --sample_id_key argument generates a broken header

### ISSUE THREAD

**Issue by tvatanen** [biobakery/MetaPhlAn#108]
If sample ID is explicitly given with --sample_id_key argument, the resulting header row is missing "#" character. Consequently merge_metaphlan_tables.py does not work (since it's looking for a header with either one of four lines starting with "#").

**Comment by fbeghini** [comment]
Unfortunately, the latest version available on conda/pip is affected by this bug, but it has been resolved in the latest version available from source. The previous versions were using as default the `SampleID` string with a leading `#`.
I'm waiting to sync conda and pip with the latest updates.

**Comment by fbeghini** [comment]
I've included the changes in 3.0.1, will be available on conda/pypi soon!
