### ISSUE TITLE
[BUG]metaphlan --install failed

### ISSUE THREAD

**Issue by minjaekim45** [biobakery/MetaPhlAn#109]
Hello
I'm trying to install metaphlan2 with the following commands

conda create --name mpa -c bioconda metaphlan
conda activate mpa
metaphlan --install 

Then, I got the following errors

Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
Downloading file of size: 0.00 MB
0.01 MB 232.33 %  11.95 MB/sec  0 min -0 sec         
Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAAyoJpOgcjop41VIHAGWIVLa/mpa_latest?dl=1
Downloading file of size: 0.00 MB
0.01 MB 31507.69 %  16.79 MB/sec  0 min -0 sec         
Downloading MetaPhlAn database
Please note due to the size this might take a few minutes

File /nv/hp10/kim45/.conda/envs/mpa/lib/python3.6/site-packages/metaphlan/metaphlan_databases/file_list.txt already present!
Traceback (most recent call last):
  File "/nv/hp10/kim45/.conda/envs/mpa/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/nv/hp10/kim45/.conda/envs/mpa/lib/python3.6/site-packages/metaphlan/metaphlan.py", line 1187, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/nv/hp10/kim45/.conda/envs/mpa/lib/python3.6/site-packages/metaphlan/metaphlan.py", line 610, in check_and_install_database
    download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
  File "/nv/hp10/kim45/.conda/envs/mpa/lib/python3.6/site-packages/metaphlan/metaphlan.py", line 463, in download_unpack_tar
    url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
KeyError: 'mpa_mpa_v30_CHOCOPhlAn_201901.tar'

Please help me with this
Thanks
Minjae

**Comment by fbeghini** [comment]
Hi, you are installing an older MetaPhlAn build. In order to use the most recent and working one, you should configure first the conda installation, if it was not already done:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```
then, 
remove the current mpa conda environment : `conda deactivate && conda env remove -n mpa`
create a new one with python 3.7: `conda create -n metaphlan-3.0 python=3.7`
install MetaPhlAn 3 in the new environment: `conda activate metaphlan-3.0 && conda install -c bioconda metaphlan`

**Comment by minjaekim45** [comment]
Thanks! It works now
Minjae
