### ISSUE TITLE
[BUG] merge_metaphlan_tables.py errors on inputs with >4 header rows

### ISSUE THREAD

**Issue by bballew** [biobakery/MetaPhlAn#113]
**Describe the bug**

Upon running the script (e.g. `merge_metaphlan_tables.py profile1.txt profile2.txt -o output.txt`), I get the following error.  

```
RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "merge_metaphlan_tables.py", line 84, in <module>
    main()
  File "merge_metaphlan_tables.py", line 78, in main
    merge(args.aistms, sys.stdout)
  File "merge_metaphlan_tables.py", line 46, in merge
    names = names,
UnboundLocalError: local variable 'names' referenced before assignment
```
I see that the variable `names` is defined conditionally in `merge_metaphlan_tables.py` on the length of a list of header rows (starting with "#"), but the conditions only cover a length of 1 or 4.  My input files have 5 header rows as follows:

```
$ head profile1.txt
#mpa_v30_CHOCOPhlAn_201901
#/path/to/miniconda3/envs/metaphlan3.0/bin/metaphlan /path/to/HMP_data/metaphlan3/sample1_un.fastq --input_type fastq --bowtie2db /path/to/database/metaphlan -t rel_ab_w_read_stats
#SampleID	Metaphlan_Analysis
#estimated_reads_mapped_to_known_clades:4265712
#clade_name	clade_taxid	relative_abundance	coverage	estimated_number_of_reads_from_the_clade
UNKNOWN	-1	65.25005	-	8009736
k__Bacteria	2	34.74995	1.97289	4265712
k__Bacteria|p__Firmicutes	2|1239	13.75146	0.78072	1569658
k__Bacteria|p__Proteobacteria	2|1224	13.44175	0.76314	1620281
k__Bacteria|p__Fusobacteria	2|32066	6.16249	0.34987	849835
```

**To Reproduce**
- Activate metaphlan3.0 environment
- run `merge_metaphlan_tables.py profile1.txt profile2.txt -o output.txt` where the input files have headers as described above

**Platform (please complete the following information):**
 - metaphlan version 3.0
 - Download source: conda

**Additional context**
This may be related to issue #98.  I tried changing line 31 to `if len(headers) >= 4:` and it runs without error on my test data, but I'm not sure what other implications this may have.

**Comment by fbeghini** [comment]
Which build have you installed?

----

Francesco Beghini

PhD Student


Lab. of Computational Metagenomics

Department of Cellular, Computational and Integrative Biology - CIBIO

University of Trento
Via Sommarive 9, 38123 Trento, Italy

Il Mar 7 Lug 2020, 18:49 Bari Ballew <notifications@github.com> ha scritto:

**Comment by bballew** [comment]
```
$ metaphlan --version
MetaPhlAn version 3.0 (25 Feb 2020)
```

**Comment by fbeghini** [comment]
The build you have installed is an older one still affected by this bug, the latest one is metaphlan-3.0.1-pyh5ca1d4c_0. Can you try update metaphlan using `conda install metaphlan=3.0.1`?

**Comment by bballew** [comment]
Thank you @fbeghini!  I'll keep an eye out for a new build on conda.

**Comment by bballew** [comment]
Hi @fbeghini - I tried running this same analysis with metaphlan-3.0.1-pyh5ca1d4c_0, and received the same error message as for 3.0.  Not sure if you just haven't gotten around to pushing a fix yet.  Thanks again!

**Comment by fbeghini** [comment]
No, still not pushed a new build, but the script in the repo is updated, if you want to replace.
I'll push a new build probably in the next days, the database installation function need to be updated.

**Comment by JustinGibbons** [comment]
Hello,

I am still getting this error after updating the merge_metaphlan_tables.py script:
`Traceback (most recent call last):
  File "merge_metaphlan_tables.py", line 10, in <module>
    sys.exit(main())
  File "merge_metaphlan_tables.py", line 78, in main
    merge(args.aistms, sys.stdout)
  File "merge_metaphlan_tables.py", line 46, in merge
    names = names,
UnboundLocalError: local variable 'names' referenced before assignment
`
I'm running MetaPhlAn version 3.0 (20 Mar 2020)

**Comment by fbeghini** [comment]
Hi @JustinGibbons , can you upload here the files you are trying to merge?

**Comment by JustinGibbons** [comment]
Hello @fbeghini,

I have attached my files
[Metaphlan_Results.zip](https://github.com/biobakery/MetaPhlAn/files/6443584/Metaphlan_Results.zip)

Thank you

**Comment by fbeghini** [comment]
Hi @JustinGibbons ,
It seems that the 3rd line of the header of the profiles is missing a heading '#', this was a bug corrected in version 3.0.1 https://github.com/biobakery/MetaPhlAn/commit/5fb4624512bda517f4cb36f2c39d8e128d58ffd1, by adding the missing "#' the profiles are correctly merged, so I suggest you to check if you are running the latest (3.0.8) version of MetaPhlAn.

Francesco

**Comment by fdavis2022** [comment]
Hello,

I am receiving the same error as @bballew:

Traceback (most recent call last):
File "merge_metaphlan_tables.py", line 84, in <module>
    main()
  File "merge_metaphlan_tables.py", line 78, in main
    merge(args.aistms, sys.stdout)
  File "merge_metaphlan_tables.py", line 46, in merge
    names = names,
UnboundLocalError: local variable 'names' referenced before assignment

It seems like this was fixed in previous versions, but I am using the script from what looks like the most recent version (https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/utils/merge_metaphlan_tables.py). Is there a different location I could download from to stop receiving this error?

**Comment by fbeghini** [comment]
> Hello,
> 
> I am receiving the same error as @bballew:
> 
> Traceback (most recent call last):
> File "merge_metaphlan_tables.py", line 84, in
> main()
> File "merge_metaphlan_tables.py", line 78, in main
> merge(args.aistms, sys.stdout)
> File "merge_metaphlan_tables.py", line 46, in merge
> names = names,
> UnboundLocalError: local variable 'names' referenced before assignment
> 
> It seems like this was fixed in previous versions, but I am using the script from what looks like the most recent version (https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/utils/merge_metaphlan_tables.py). Is there a different location I could download from to stop receiving this error?
Hi @fdavis2022, can you upload here the files you are trying to merge?
