### ISSUE TITLE
Request: option to never download databases

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [biobakery/MetaPhlAn#118]
Hi,

Thanks for your work on Metaphlan2. I'm currently using metaphlan2 within a docker container, with a precompiled reference database that is baked into the container itself. It would be nice to pass an option to metaphlan2 to have it abort if it doesn't find the database specified at --index to avoid download attempts. Looks like it would be a simple modification of the check_and_install function in the package.

Let me know if you need more detail. It's not critical for our applications but would help ensure failure in case where we've misconfigured the db.

**Comment by fbeghini** [comment]
Hi,  in https://github.com/biobakery/MetaPhlAn/commit/7af2ecfab69e0ec5e553fbf5d144ba7cbf50c871 I've added a `--offline` flag for the metaphlan2.py script, if the DB files are not found in the `bowtie2db` folder, the execution is halted and exits with an error.

**Comment by jdwinkler-lanzatech** [comment]
Great! Thank you for your help.
