### ISSUE TITLE
Conda MetaPhlAn versions are outdated

### ISSUE THREAD

**Issue by MingL196** [biobakery/MetaPhlAn#120]
I tried installing MetaPhlAn through Conda, as recommended in the tutorial.

It turns out that Conda only has version 2.7.8 and 2.96.1, both of which tries to download from bitbucket.

=========

In the end, I cloned GitHub. This version successfully downloaded from dropbox.

**Comment by fbeghini** [comment]
Version 2.8 of MetaPhlAn2 retrieves the database from Dropbox and is available if the version is specified.
