### ISSUE TITLE
Question on abundance output

### ISSUE THREAD

**Issue by dylan-lawrence** [biobakery/MetaPhlAn#122]
I have not been able to find a clear answer on this and wanted to get some clarification on exactly how percent abundance is calculated in the output.

If a read file contains no classifiable samples it will output as:

`unclassified	100.0`

Where as classified files look more like

`k__Bacteria	100.0
k__Bacteria|p__Firmicutes	100.0
k__Bacteria|p__Firmicutes|c__Clostridia	100.0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales	100.0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae	100.0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Coprococcus	92.46904
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Dorea	7.15602
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Blautia	0.37494
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Coprococcus|s__Coprococcus_comes	92.46904
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Dorea|s__Dorea_unclassified	7.15602
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Blautia|s__Ruminococcus_torques	0.37494
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Coprococcus|s__Coprococcus_comes|t__GCF_000155875	92.46904
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Blautia|s__Ruminococcus_torques|t__Ruminococcus_torques_unclassified	0.37494`

In the latter case, does this mean every read was classified, or are the unclassified reads not counted in this percentages? And, if the latter is true (that unclassified is not counted) would it be possible to implement a flag to allow for this output to account for unclassified reads as well?

**Comment by fbeghini** [comment]
>unclassified 100.0
means that MetaPhlAn was not able to identify enough markers or no markers at all to profile the metagenome.

When you have a profile with one or more species, MetaPhlAn was able to classify just a subset of reads, the total is automatically scaled to the total amount of classified reads.
You can have a sense on how many unclassified reads are present by using the `--unknown_estimation` parameter, which will use as denominator the total number of reads instead the total profiled ones.
