### ISSUE TITLE
how to calculate the coverage and abundance

### ISSUE THREAD

**Issue by QuanLG** [biobakery/MetaPhlAn#126]
Hello,developers:
        This is my comand ：
             metaphlan2.py all_clean_paired.fastq --bowtie2out sample_bowtie2_out.txt -s sample_bowtie2.sam 
--nproc 20 --nreads 20 --input_type fastq    **-t rel_ab_w_read_stats** > sample_profile.txt  . 
And the output like this 
#SampleID       Metaphlan2_Analysis
#clade_name     **relative_abundance**      **coverage**        average_genome_length_in_the_clade      estimated_number_of_reads_from_the_clade
k__Bacteria     99.79795        0.647533178273  3060646 1981870
k__Eukaryota    0.20205 0.00131097628568        30631893        40158
k__Bacteria|p__Firmicutes       60.12608        0.39012454115   2645593 1032111
k__Bacteria|p__Proteobacteria   39.67187        0.257408637123  3135748 807169
k__Eukaryota|p__Ascomycota      0.17011 0.00110375275938        42640228        47064
k__Eukaryota|p__Basidiomycota   0.03194 0.000207223526301       27723717        5745

can you tell me how to calculate the coverage and relative_abundance,I am a litter confused

**Comment by fbeghini** [comment]
What do you mean with how to calculate the coverage and relative_abundance?

**Comment by QuanLG** [comment]
I  have found the answer on web :  https://forum.biobakery.org/t/metaphlan3-relative-abundance/564/2
