### ISSUE TITLE
running fasta file with metaphlan3 but empty output

### ISSUE THREAD

**Issue by mars188** [biobakery/MetaPhlAn#127]
Hi, 

I have successfully installed metaphlan 3 (I think). When I downloaded "SRS014476-Supragingival_plaque.fasta.gz file from the online tutorial then it works fine. I was able to get the results until heatmap. However, when I tried my own real fasta file, it generated empty output. The output files looks like this:

#SampleID       Metaphlan_Analysis
#clade_name     NCBI_tax_id     relative_abundance      additional_species
UNKNOWN -1      100.0

My command is as below:
`metaphlan final_assembly.fasta --input_type fasta > ctrl_A_profile.txt`

Can anyone please help me what is the difference between running these two fasta files? and why I am getting empty output file?

Thanks in advance.

**Comment by fbeghini** [comment]
Hi, 
MetaPhlAn is supposed to be run using metagenomic reads and not using an assembled genome, you should run it using the reads you used for assemble the fasta.

**Comment by mars188** [comment]
You mean it only accepts raw reads? like .fastq?

Then for example, I have 10 groups and 50 replications (raw fastq reads) from each group. There are total like 500 raw reads. Should I process them individually? and later merge them? I was hoping to be able to compare only 10 groups (on group basis) and not 500 samples (not sample basis)... 

Would appreciate your help in this regard.

Many thanks

**Comment by kescobo** [comment]
@mars188 This type of question may be better suited for the [discussion forums](https://forum.biobakery.org/c/Microbial-community-profiling/MetaPhlAn/7). 

But yes, typically metaphlan would be run on each sample separately. If you really don't care about separating replicates, you could concatenate all of the replicate fastqs together. But the goal of this software is to get the relative abundance of individual taxa based on how many reads are hitting them - if you try to pass an assembly, this information is lost.

**Comment by mars188** [comment]
Great, thank you so much for clarifying this. I will now try to figure out what to do. Thanks again.

**Comment by timyerg** [comment]
Hello guys.
I am trying to run metaphlan with raw paired reads. The run completes successfully but the output profiled_metagenome.txt file is empty. At the same time, bowtie2.bz2 is not empty. Could you help me?
My command is:
`metaphlan2.py inp1.fastq.gz inp2.fastq.gz --bowtie2out bowtie2.bz2 --nproc 4 --input_type fastq > profiled_metagenome.txt `

**Comment by fbeghini** [comment]
Please see #123
