### ISSUE TITLE
Different output for metaphlan2 and metaphlan3

### ISSUE THREAD

**Issue by mflynn-lanl** [biobakery/MetaPhlAn#128]
**Describe the bug**
I get different results when I run metaphlan2 and metaphlan3 on the same fastq file. The results file from metaphlan2 identifies an ebolavirus, as do other taxonomic profilers. However, the output file for metaphlan3 only has UNKNOWN   

**To Reproduce**
`docker run -it --rm -v /Devel/metaphlan/:/data quay.io/biocontainers/metaphlan:3.0.4--pyh7b7c402_0`
`/ # metaphlan --input_type fastq /data/test.fastq /data/metaphlan_report.txt`
I've attached the fastq file, report file and bowtie2 output file:
[metaphlan3.zip](https://github.com/biobakery/MetaPhlAn/files/5329092/metaphlan3.zip)

`docker run -it --rm -v /Devel/metaphlan/:/data quay.io/biocontainers/metaphlan2:2.8--py_0`
`/ # metaphlan2.py --input_type fastq /data/test.fastq /data/metaphlan2_report.txt`
[metaphlan2.zip](https://github.com/biobakery/MetaPhlAn/files/5329094/metaphlan2.zip)

I've also had this problem when installing using conda

**Platform (please complete the following information):**
 - Version 3.04
 - Download source quay.io/biocontainers/metaphlan

**Comment by kescobo** [comment]
This is not a bug - the two versions use very different databases.

Also, please note #123
