### ISSUE TITLE
Running with paired-end data generates bowtie file but not txt file

### ISSUE THREAD

**Issue by flannsmith** [biobakery/MetaPhlAn#130]
**Describe the bug**
At first I thought I was running the program wrong but I've noticed that when passing in paired-end sequences to metaphlan the bowtie file is generated but the text file is empty. I can just run metaphlan again on the generated bowtie file but would be handy if the txt file was produced as well.  

**To Reproduce**

`metaphlan2.py E5b_S84_p1.fastq.gz E5b_S84_p2.fastq.gz --bowtie2out ./metaphlan_output/bowtie_out/E5b_S84.bowtie2.bz2 --input_type fastq > ./metaphlan_output/E5b_S84_profile.txt `

**Platform (please complete the following information):**
- Using Python 3.6.9 on Linux 
- MetaPhlAn version 2.8.1 (23 Jul 2020)
- Download source [git]

**Comment by fbeghini** [comment]
Hi, in order to use paired end reads, you need to provide them as a comma separated list, e.g. `metaphlan2.py E5b_S84_p1.fastq.gz,E5b_S84_p2.fastq.gz`
