### ISSUE TITLE
[BUG] MetaPhlan3 produces no bowtie2out

### ISSUE THREAD

**Issue by iquasere** [biobakery/MetaPhlAn#132]
**Describe the bug**
metaphlan3 does not produce bowtie2out with FastQ input, nor it produces an error report. However, if I stop the command mid run, a bowtie2out is produced, and taxonomic classification is correct. Likely, MetaPhlan is removing the file at the end of execution, for some reason

**To Reproduce**
```metaphlan path/to/R1.fq,path/to/R2.fq --bowtie2out path/to/mg.bowtie2.bz2 --nproc 14 --input_type fastq```

**Screenshots**
Output directory (path/to/) is just empty

**Platform (please complete the following information):**
 - Version: 3.0.5
 - Download source: ```conda install -c conda-forge -c bioconda metaphlan=3```

**Comment by fbeghini** [comment]
If you provide an output path via the `-o` parameter, does it generate a report? Can you see from `top`/`htop` if `bowtie2` is running?

**Comment by iquasere** [comment]
If first ran with the -o, and the result was the same. Then I tried splitting into two command, first generate the bowtie2out than use that as input to use the -o, but bowtie2out was not there

**Comment by iquasere** [comment]
Tested now observing htop, and bowtie2 runs to the end, with the alignment result growing, until it vanishes

**Comment by fbeghini** [comment]
I'm sorry but I cannot reproduce your issue. In both cases, even if `bowtie2out` is not specified, the bowtie2out should be generated.

**Comment by iquasere** [comment]
You cannot reproduce it in a clean environment? If you could provide me the conda list output, I could track the dependency that might be screwing this

**Comment by fbeghini** [comment]
Yes, that's right. Here attached the conda list output. Otherwise, can you upload somewhere the input files so I can do more testing?
[conda_list.txt](https://github.com/biobakery/MetaPhlAn/files/5589145/conda_list.txt)
