### ISSUE TITLE
Issue for database file full_chocophlan.v296_201901.tar.gz

### ISSUE THREAD

**Issue by deminu** [biobakery/MetaPhlAn#137]
Hi, I want to analysis some metagenome data using metaphlan3. But the result only contain bacteria. It seems like full_chocophlan.v296_201901.tar.gz only contain 10669 bacteria fnn files. Is this ture? If it is, which one is the full database containing fungal and viruses?

**Comment by fbeghini** [comment]
`full_chocophlan.v296_201901.tar.gz` is the file with the pangenomes used by HUMAnN and also includes fungi, not viruses. The MetaPhlAn databases can be retrieved from [here](https://zenodo.org/record/3957592) and includes fungi and viruses.

**Comment by deminu** [comment]
Ok, thank you. Is it proper using MetaPhlAn databases from https://zenodo.org/record/3957592 instead of full_chocophlan.v296_201901.tar.gz when I run HUMAnN pipeline?

**Comment by fbeghini** [comment]
What do you mean? `full_chocophlan.v296_201901.tar.gz` contains the
pagenome files for HUMAnN, while `mpa_v30_CHOCOPhlAn_201901.tar` contains
the marker files for MetaPhlAn.
----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

ᐧ

**Comment by deminu** [comment]
My understanding may be wrong. In the taxomonic profiling step of  HUMAnN, it also use the database `mpa_v30_CHOCOPhlAn_201901.tar'. But `full_chocophlan.v296_201901.tar.gz` is used for gene family abundance at the community level analyzing. They are created for different porpuse. Does it right?

**Comment by fbeghini** [comment]
Yes, the taxonomic filtering is performed with
` mpa_v30_CHOCOPhlAn_201901.tar` and the profiles for bacteria, archaea,
eukaryotes, and viruses. Functional annotated pangenomes (`
full_chocophlan.v296_201901.tar.gz`) are available for all the kingdoms
except for viruses.
----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

ᐧ

**Comment by deminu** [comment]
Ok, I got it. Thank you !
