### ISSUE TITLE
[BUG] rel_ab_w_read_stats with --add_viruses throws KeyError: 'PRJNA14242'

### ISSUE THREAD

**Issue by ssorgatem** [biobakery/MetaPhlAn#138]
Since this looks like a bug, I decided to open an issue for it.
The issue seems to happen when the bowtie2 alignmenrt file was generated with "-t rel_ab_w_read_stats", since I get the same error if I use that alignment file and "-t rel_ab"; while if I directly use the source fastq with "-t rel_ab" and "--ad_viruses" I don't get any error (but then I don't get the estimated read counts...)

Here's a bowtie2 alignment file that triggers the issue: https://actinia.xyz/index.php/s/AGXbbHqEkWLZKCg

Here's the full trace with metaphlan 3.0.6:

    > metaphlan metaphlan_bowtie2.txt ktest_relab_ws --input_type bowtie2out -t rel_ab_w_read_stats --mdelim ";" --add_viruses                                                                                           
    > Traceback (most recent call last):
    >   File "/zpool_1TB/lib/miniconda3/bin/metaphlan", line 10, in <module>
    >     sys.exit(main())
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1127, in main
    >     pars['tax_lev']+"__" if pars['tax_lev'] != 'a' else None )
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 739, in relative_abundances
    >     tot_ab += clade.compute_abundance()
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    >     sum_ab = sum([c.compute_abundance() for c in self.children.values()])
    >   File "/zpool_1TB/lib/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 535, in compute_abundance
    >     ext_clade = self.taxa2clades[ext]
    > KeyError: 'PRJNA14242'

I've also encountered that for a different fastq file so far, but the key not found is a different one: PRJNA16327

**Comment by fbeghini** [comment]
Yes, that's right, it is missing an entry for the genome associated to PRJNA16327. I'll fix this ASAP and patch the pickle file.

**Comment by ssorgatem** [comment]
Thanks for your quick reply.
So far the missing entries I've found are:
PRJNA14242
PRJNA202888
PRJNA16327

There may be more.

**Comment by fbeghini** [comment]
Hi @ssorgatem ,
I've uploaded the cleaned pickle file, you can find it [here](http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/)

**Comment by ssorgatem** [comment]
Great! Thank you! It works now, for all the samples I had trouble with.
