### ISSUE TITLE
[BUG] Program fails when using BowTie2 SAM input and analysis type "rel_ab_w_read_stats"

### ISSUE THREAD

**Issue by alexhbnr** [biobakery/MetaPhlAn#139]
Hi,

I have the following problem that I would like to change the parameters of BowTie2 that are used for aligning the data. Since `metaphlan` currently only allows to use the BowTie2 presets but not to individually alter any of the underlying values, I went ahead and manually aligned the sequencing data to the marker-gene catalogue with the tweaked BowTie2 input parameters.

When I now use the SAM file of BowTie2 as the input and specify the analysis type as **"rel_ab_w_read_stats"**, `metaphlan` fails because it cannot correctly calculate the number of unmapped reads.

```
Traceback (most recent call last):
  File "/home/alexhbnr/miniconda3/envs/MetaPhlAn3_HUMAnN3/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/home/alexhbnr/miniconda3/envs/MetaPhlAn3_HUMAnN3/lib/python3.8/site-packages/metaphlan/metaphlan.py", line 1130, in main
    unmapped_reads = max(n_metagenome_reads - tot_nreads, 0)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

I provided manually the number of input reads into BowTie2 using `--nreads`, however, the part of the code that copies the information from the commandline parameter `--nreads` (`pars['nreads']`) to `n_metagenomic_reads is put behind an if-clause that requires the commandline parameter `--unknown_estimation` to be set to `True` ([l. 1017](https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/metaphlan.py#L1017)) .

I personally don't want to estimate the proportion of unknown, so I removed this part of the if-clause and it now works fine. But I am not sure if this is a design decision or a bug?

**Comment by fbeghini** [comment]
Hi Alex,
Yes, this was a bug, you are right, thank you for spotting this, I've pushed a fix for this.
