### ISSUE TITLE
UNKNOWN too high

### ISSUE THREAD

**Issue by dangchenyuan** [biobakery/MetaPhlAn#140]
Why the percentage of UNKNOWN is so high?
![微信截图_20210305154705](https://user-images.githubusercontent.com/45260772/110084650-2bb44680-7dcb-11eb-9851-d936c603231e.png)

**Comment by fbeghini** [comment]
Please read #123 and provide more information regarding your input.

**Comment by fanninpm** [comment]
Have you tried running your data through KRAKEN?
