### ISSUE TITLE
run all clades once

### ISSUE THREAD

**Issue by Biofarmer** [biobakery/MetaPhlAn#143]
Hello,

I am moving from StrainPhlAn2 to StrainPhlAn3, and one question is whether flag --clade in StrainPhlAn3 is mandatory or not? If yes, and I want to investigate all clades without defining specific extracted markers from MetaPhlAn database and reference-genomes, what shoud I do? 
strainphlan -s consensus_markers/*.pkl -o output -n 8 -c **xxx?** --phylophlan_mode accurate --mutation_rates

Many thanks
Wang

**Comment by fbeghini** [comment]
See #123
