### ISSUE TITLE
Database and bowtie issues

### ISSUE THREAD

**Issue by WebBach** [biobakery/MetaPhlAn#145]
Hi, I'm trying to use metaphlan 3.0 to calculate the microbial community abundance of my samples. But I get an error that I can't solve. I did an iteration for loop over each sample just to visualize better the dynamics of the run. But the idea is to run them in parallel.
The code is based on your guidance:

metaphlan metagenome_1.fastq,metagenome_2.fastq --bowtie2out metagenome.bowtie2.bz2 --bowtie2db <database folder> --nproc 5 --input_type fastq -o profiled_metagenome.txt

![image](https://user-images.githubusercontent.com/81460544/112712832-29c53b00-8ed2-11eb-8805-2e19fddf13dc.png)

But I get this repeated error in each sample:

![image](https://user-images.githubusercontent.com/81460544/112712952-e1f2e380-8ed2-11eb-9c58-18c17a3be7d5.png)

My question are: 
1) why does it try o download the database every time that runs the code if I already specify the database folder?
2) how can I solve this bowtie error?

Thank you

**Comment by fanninpm** [comment]
Try typing the `--bowtie2db` argument without the trailing slash.

**Comment by WebBach** [comment]
Hey, thanks for the suggestion but I still get exactly the same error :(

**Comment by Juliane-W** [comment]
I'm having the same issue when installing the tool:
metaphlan --install --bowtie2db [folderpath]

![image](https://user-images.githubusercontent.com/46549848/114033396-225c4500-9875-11eb-85d0-2d41cdc3079a.png)

Any suggestions on how to solve this?

**Comment by fbeghini** [comment]
Please use the BioBakery forum for asking for help. See #123 .
