### ISSUE TITLE
--force_download

### ISSUE THREAD

**Issue by nick-youngblut** [biobakery/MetaPhlAn#158]
It appears that metaphlan will not actually force re-install of the database if the exist db is within 1 year:

```
# within `resolve_latest_database()` function
if os.path.exists(os.path.join(bowtie2_db,'mpa_latest')):
       ctime_latest_db = int(os.path.getctime(os.path.join(bowtie2_db,'mpa_latest')))
       if int(time.time()) - ctime_latest_db > 31536000:         #1 year in epoch
           os.rename(os.path.join(bowtie2_db,'mpa_latest'),os.path.join(bowtie2_db,'mpa_previous'))
          download(mpa_latest_url, os.path.join(bowtie2_db,'mpa_latest'), force=True)
```

...so the user cannot actually force the re-install, in some circumstances, if they wish to do so. It would at least help to include logging info on why the `--force_download` was overruled.

**Comment by MalbertRogers** [comment]
Is it possible to turn off this --force_download (for the sake of reproducibility). I would like to have the choice to manually update the database if desired.
