### ISSUE TITLE
Database already present error

### ISSUE THREAD

**Issue by cirodri1** [biobakery/MetaPhlAn#160]
I am currently using MetaPhlAn version 3.0.13 which I downloaded through conda install. As instructed in the manual, I downloaded the database in a folder outside the Conda environment, by running this:
$ metaphlan --install --bowtie2db <database folder>

Then I tried the following code with two fastq.gz forward and reverse reads for one sample and indicated the database location as follows:
$ metaphlan P001-READ1-Sequences.txt.gz,P001-READ2-Sequences.txt.gz --bowtie2db /data/homezvol2/cirodri1/bowtie2db_folder --bowtie2out metagenome.bowtie2.bz2 --input_type fastq -o profiled_metagenome.txt

But when running that code I get the following error: 
<img width="926" alt="Screen Shot 2021-10-25 at 2 07 42 PM" src="https://user-images.githubusercontent.com/36938244/138771081-5c174bda-8987-486d-b87c-df2bf8452ca9.png">
:
 I have been checking through the issues channel and found a similar issue #157 but the issue was closed by the user without a solution. 
 
Then, I tried running the following code on the same set of fastq.gz files:
$ for f in .gz*
do
    echo "Running metaphlan 3.0 on ${f}"
    bn=$(basename ${f%fastq.bz2})
    metaphlan $f --input_type fastq -s sams/${bn}.sam.bz2 --bowtie2db /data/homezvol2/cirodri1/bowtie2db_folder --bowtie2out bowtie2/${bn}.bowtie2.bz2 -o profiles/${bn}_profile.tsv 
done

and I obtained the following error:
<img width="926" alt="Screen Shot 2021-10-25 at 2 21 27 PM" src="https://user-images.githubusercontent.com/36938244/138772828-e952c545-fada-40a8-91b9-704ebd2bb47c.png">

 Can anyone guide me into making my Metaphlan work correctly and locate the database. Thank you!

 - Version: 3.0.13
 - Download source through conda create --name mpa -c bioconda python=3.7 metaphlan
 - I am running the program from a remote server and inside a miniconda self-made environment.

**Comment by fbeghini** [comment]
@cirodri1 , can you run separately the bowtie2-build command to see what error has been raised?
The error you get when you try to run MetaPhlAn afterwards is raised because no Bowtie2 database files can be found.

**Comment by YANWF2020** [comment]
me too!!!!! I encountered the same problem! May I ask whether it was solved? anyone could provide a solution?

**Comment by YANWF2020** [comment]
> You can do that, but I was able to just install `tbb` to my existing environment. With the environment active, just try doing `bowtie2 --help` to make sure it works when you're done

I also encountered this problem. and I used this method from Mr.kescobo, and the problem of the database was solved! Thank you so much, Mr.kescobo and cirodri1!
