### ISSUE TITLE
L. casei & B. subtilis group not present in MetaPhlAn 3

### ISSUE THREAD

**Issue by Adrian-Howard** [biobakery/MetaPhlAn#161]
**Whole species groups like Lactobacillus casei group not present in MetaPhlAn 3**
I have tried to use MetaPhlAn with samples that have Bacillus subtilis and Lactobacillus casei but in the profile tables they are not present.

I have found this paper where they say that "multiple species included by the NCBI taxonomy into a ‘species-group’ are identified with unique markers for the whole species groups such as Lactobacillus casei group, Bacillus subtilis group..."
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8096432/

But when I run metaphlan with the database mpa_v30_CHOCOPhlAn_201901 this species groups arent shown and my relative abundances are computed with out this species...

How can I get a profile table with the relative abundances of these species groups?

**Comment by fbeghini** [comment]
We are aware of this problem, something went wrong while re-packing the
database and we are working on it. Unfortunately, these were the only two
species groups that were lost.

*Francesco Beghini, PhD*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy
