### ISSUE TITLE
Problems about species absence and new information about database update

### ISSUE THREAD

**Issue by MGI-EU** [biobakery/MetaPhlAn#162]
Hi,

I'm using metaphlan to analyze our samples and compare it with results generated by other tools. I found several species not present in latest version of dataset (listed as following). 

Two species (*cremea* and *lutea* ) are published after 2019, while the latest dataset was created in 2019 as it's said in #116 . But the other three are published far before 2018 . The whole family of "*Faecalibacillus*" doesn't exist. The issue #161 has similar question about different family. The "*Nocardioides*" family has only other homologous species existed in the dataset.

Based on these, I have these questions:

**1. How do you choose which species to be remained ? By marker number, genome completeness or other key feature ?**
**2. (Similar to question 1) Are you going to incorporate as many new species as possible ? Or will just select the representative species/strain.**
**3. Is there any webpage or note or site that show the trajectory/roadmap of the database update?**
**4. Will you publish your new database generation pipeline, which may help users customize more reliable database ?**

Absent species:
- *Actinomadura cremea* ([NCBI link](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=31961))
- *Aequorivita lutea* ([NCBI link](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2610884))
- *Faecalibacillus intestinalis* ([NCBI link](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1982626))
- *Nocardioides agariphilus* ([NCBI link](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=433664))
- *Nocardioides islandensis* ([NCBI link](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=433663))

**Comment by fbeghini** [comment]
>    - Actinomadura cremea (NCBI link
>    <https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=31961>)
>
>
>    - Aequorivita lutea (NCBI link
>    <https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2610884>)
>
> As you said, they were published after Jan 2019, so were not included.
Aequorivita lutea has now a proteome entry on  UniProt, while A. cremea is
not present on UniProt.

>
>    - Faecalibacillus intestinalis (NCBI link
>    <https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1982626>)
>
> At the date of processing, this species was named Lachnoclostridium sp.
SNUG30099 with NCBI taxid 2126738 and was discarded due to a low number of
markers.

>
>    - Nocardioides agariphilus (NCBI link
>    <https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=433664>)
>
>
>    - Nocardioides islandensis (NCBI link
>    <https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=433663>)
>
> Same situation as A. cremea, no UniProt proteome present.

*2. (Similar to question 1) Are you going to incorporate as many new
> species as possible ? Or will just select the representative
> species/strain.*

We tried to include as many species as possible, with no distinction of
representative species. If some species are missing, the reason can imputed
to the low number of markers or an high number of non-specific markers.


> *3. Is there any webpage or note or site that show the trajectory/roadmap
> of the database update?*

Unfortunately, no.

**Comment by MGI-EU** [comment]
Thank you for your reply ! It's clear now.

Looking forward to your update !

I will close this issue.
