### ISSUE TITLE
metaphlan2krona.py not working

### ISSUE THREAD

**Issue by andreott** [biobakery/MetaPhlAn#163]
Hi,

metaphlan2krona.py fails as it does not expect the additional species field. For me I used the trivial fix locally by adding line 37 
```python
aline = '\t'.join(aline.split('\t')[:-1])
```

https://github.com/biobakery/MetaPhlAn/blob/46ef712a590faca541e9fa293eda891216d39994/metaphlan/utils/metaphlan2krona.py#L35-L42

**Comment by fbeghini** [comment]
Thank you for reporting this, if you are willing to add this fix into a PR, I'll approve it.
