### ISSUE TITLE
md5 check of mpa_v30_CHOCOPhlAn_201901.tar output doesn't match mpa_v30_CHOCOPhlAn_201901.md5

### ISSUE THREAD

**Issue by MGI-EU** [biobakery/MetaPhlAn#164]
Hi, developer,

According to the [Wiki page of MetaPhlAn3.0 installation](https://github.com/biobakery/MetaPhlAn/wiki/MetaPhlAn-3.0#installation) , users can download packed db from [google drive link](https://drive.google.com/drive/folders/1_HaY16mT7mZ_Z8JtesH8zCfG9ikWcLXG) .

As the title said, however, the `mpa_v30_CHOCOPhlAn_201901.tar` file failed in md5 check. Here is what I have:

```shell
md5sum mpa_v30_CHOCOPhlAn_201901.tar
# output: ef1031fb8dc60775e24bd13ada42da99 mpa_v30_CHOCOPhlAn_201901.tar

cat mpa_v30_CHOCOPhlAn_201901.md5
# output: cd4305c06c840d8a34ab1a6f5afa08b3 mpa_v30_CHOCOPhlAn_201901.tar
```

**Comment by fbeghini** [comment]
Sorry about this, I'll check what went wrong.
Are you able in the meantime to fetch the database from
http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/ ?

Best,
*Francesco Beghini, PhD*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

**Comment by MGI-EU** [comment]
Hi,

Thank you for the suggestion. Yes I've downloaded it. The tar file has the same md5 as that in `.md5` file.

But the md5 value is different from both of the .tar and .md5 from files in Google Drive. Also, after I extract the bz2 and pkl, each pair of them has different md5.

I my humble opinion, if possible, it could be better if all the md5 values of corresponding files, both tar and bz2/pkl, are equal.

Thank you !
