### ISSUE TITLE
strainphlan 

### ISSUE THREAD

**Issue by valei** [biobakery/MetaPhlAn#165]
Hi,
I'm running strainphlan on my Centos7 system. I accurately followed the guide I found here. I got this error message "No alignments found to concatenate" and "An error was ocurred executing a external tool, exiting..."
I wonder, what means the message? And, what is the external tool returning an error?
Please, help me. 
Valentina

strainphlan -s consensus_markers/*.pkl -m db_markers/s__Lactobacillus_fermentum.fna  -o output -n 4 -c s__Lactobacillus_fermentum --mutation_rates
Wed Dec  1 12:37:55 2021: Start StrainPhlAn 3.0 execution
Wed Dec  1 12:37:55 2021: Creating temporary directory...
Wed Dec  1 12:37:55 2021: Done.
Wed Dec  1 12:37:55 2021: Getting markers from main sample files...
Wed Dec  1 12:37:55 2021: Done.
Wed Dec  1 12:37:55 2021: Getting markers from main reference files...
Wed Dec  1 12:37:55 2021: Done.
Wed Dec  1 12:37:55 2021: Removing bad markers / samples...
Wed Dec  1 12:37:55 2021: Done.
Wed Dec  1 12:37:55 2021: Writing samples as markers' FASTA files...
Wed Dec  1 12:37:56 2021: Done.
Wed Dec  1 12:37:56 2021: Writing filtered clade markers as FASTA file...
Wed Dec  1 12:37:56 2021: Done.
Wed Dec  1 12:37:56 2021: Calculating polymorphic rates...
Wed Dec  1 12:37:56 2021: Done.
Wed Dec  1 12:37:56 2021: Executing PhyloPhlAn 3.0...
Wed Dec  1 12:37:56 2021:       Creating PhyloPhlAn 3.0 database...
Wed Dec  1 12:37:56 2021:       Done.
Wed Dec  1 12:37:56 2021:       Generating PhyloPhlAn 3.0 configuration file...
Wed Dec  1 12:37:56 2021:       Done.
Wed Dec  1 12:37:56 2021:       Processing samples...[e] "/usr/local/lib/python3.7/site-packages/phylophlan/phylophlan_configs/" folder does not exists

[e] No alignments found to concatenate

[e] An error was ocurred executing a external tool, exiting...
Wed Dec  1 12:37:58 2021: Stop StrainPhlAn 3.0 execution.

**Comment by fbeghini** [comment]
Can you check if you have the latest version of phylophlan installed? You can create that folder and then run from there phylophlan_write_default_configs.sh
