### ISSUE TITLE
Metaphlan2 could annotated 100% bacteria but metaphlan3 annotated 100% UNKNOWN

### ISSUE THREAD

**Issue by zhaoxvwahaha** [biobakery/MetaPhlAn#166]
Hi,

The database of metaphlan3 is several times bigger than metaphlan2, why for my same fq file, Metaphlan2 could annotated 100% bacteria but metaphlan3 annotated 100% UNKNOWN.

Following is the detailed comands and results:
metaphlan p1.fq.gz,p2.fq.gz --input_type fastq -o R2104021086.MPA3.profiled_metagenome --nproc 4 --bowtie2out R2104021086.MPA3.metagenome.bowtie2.bz2 --bowtie2db metaphlan_databases --index mpa_v30_CHOCOPhlAn_201901

The R2104021086.MPA3.profiled_metagenome is:
#SampleID       Metaphlan_Analysis
#clade_name     NCBI_tax_id     relative_abundance      additional_species
UNKNOWN -1      100.0

$less -S R2104021086.MPA3.metagenome.bowtie2.bz2|wc -l
66103
$less -S R2104021086.MPA3.metagenome.bowtie2.bz2|tail -2
#nreads 7046594
#avg_read_length        150.0

Any help will be appreciated, thanks in advance.

**Comment by zhaoxvwahaha** [comment]
When I used metaphlan2, the result is 100% bacteria:

#SampleID       Metaphlan2_Analysis
k__Bacteria     100.0
k__Bacteria|p__Proteobacteria   100.0

**Comment by fbeghini** [comment]
Can you provide the full MetaPhlAn2 output profile? I would assume that the (sole) species in MetaPhlAn2 was identified using a genus-level marker, which are no longer used in version 3

**Comment by zhaoxvwahaha** [comment]
Hi @fbeghini,
The complete content of mysample.profiled_metagenome is:
#SampleID       Metaphlan2_Analysis
k__Bacteria     100.0
k__Bacteria|p__Proteobacteria   100.0
k__Bacteria|p__Proteobacteria|c__Alphaproteobacteria    100.0
k__Bacteria|p__Proteobacteria|c__Alphaproteobacteria|o__Rickettsiales   100.0
k__Bacteria|p__Proteobacteria|c__Alphaproteobacteria|o__Rickettsiales|f__Anaplasmataceae        100.0
k__Bacteria|p__Proteobacteria|c__Alphaproteobacteria|o__Rickettsiales|f__Anaplasmataceae|g__Wolbachia   100.0
k__Bacteria|p__Proteobacteria|c__Alphaproteobacteria|o__Rickettsiales|f__Anaplasmataceae|g__Wolbachia|s__Wolbachia_unclassified 100.0

**Comment by fbeghini** [comment]
In this case, Wolbachia was identified using a set of genus-level markers, which no longer are present in version 3. There are markers for different Wolbachia species in version 3, but probably no one of them are the specific for the species in your metagenome
