### ISSUE TITLE
Customizing Chochophlan panproteome and Metaphlan marker gene databases with new taxa

### ISSUE THREAD

**Issue by blostein** [biobakery/MetaPhlAn#167]
[I made this post originally on the biobakery support forum but got no response](https://forum.biobakery.org/t/customizing-chochophlan-panproteome-and-metaphlan-marker-gene-databases-with-new-taxa/2814), reposting here. 

**The problem:** I’m currently working on a metagenomics project with a Zymo Spike-In which incorporates three taxa. _Trupera radiovictrix_ & _Imtechella haloterans_ are in the Chochophlan/metaphlan databases. The problem is _Allobacillus halotolerans_, which is not. Although _Allobacillus halotolerans_ IS in the NCBI taxonomy database (and has been since 2011) it does not seem to be in UniRef 90 (which is why it isn't in Chochophlan/metaphlan). 

I'm trying to follow the advice at the end of issue #103 to add a new taxa to the reference database: 

> Of course this works for genomes included in Uniprot. In case of MAGs,
annotation with DIAMOND/mmseqs2 is an alternative. For annotating MAGs, I
use DIAMOND on the proteins obtained with prokka, using evalue 1, coverage
0.8 and identity percentage 90%, the same thresholds that defines UniRef90
clusters.

**What I have done**:  I have a .fna of all the CDS/protein coding sequencing (nucleotide sequences) from the taxa. For metaphlan database, I know I need to extract marker genes from the CDS fasta file for _Allobacillus halotolerans_. I know that marker genes should be universal within the clade and unique to the clade. Once I have a fasta file of marker genes, I know I can follow the instructions [here](https://github.com/biobakery/MetaPhlAn/wiki/MetaPhlAn-3.0#customizing-the-database) to add them to metaphlan. 

**My questions**: 

1. Do I now just add the fasta of the CDS from my taxa of interest to the chochophlan database of species pan proteomes *.fnn.gz to update the chocophlan database?
2. For metaphlan database, I’m confused as to how to extract marker genes. Which database should I map my fasta file of CDS from _Allobacillus halotolerans_ against using DIAMOND, following the advice of github issue 103? Should I make a diamond binary database of the fasta file of existing Metaphlan marker genes, and map against that, then select out the sequences that do not map as marker genes? Or against UniRef 90? I tried mapping against the uniref90_201901b_full.dmnd provided with Humann and got 0 hits when using parameters --evalue 1 --id 0.9 --query-cover 0.8. Do I need to use amino acid sequences instead?

**Comment by fbeghini** [comment]
Hi @blostein, sorry for the late reply on the biobakery forum, I posted a reply just  now
