### ISSUE TITLE
[BUG] - merge_metaphlan_tables.py not working in 3.0.14

### ISSUE THREAD

**Issue by chadstachowicz** [biobakery/MetaPhlAn#173]
After running metaphlan, files with headers are generated however merge_metaphlan_tables.py utility always gives the error below:

merge_metaphlan_tables found tables without a header including the database version. Exiting.

It appears to be that somehow the merge_metaphlan_tables.py script no longer notices the format of the header file.

**Platform (please complete the following information):**
pip install metaphlan 
3.0.14

file example created from metaphlan:

#mpa_v30_CHOCOPhlAn_201901
#/Users/chadstachowicz/opt/anaconda3/bin/metaphlan --input_type fastq /Users/chadstachowicz/Downloads/meta/19APR2016HiSeq_Run_Sample_ATE_51_UNCC_Gibas_TTAGGCAT_L006_R1_001-sampled.fastq,/Users/chadstachowicz/Downloads/meta/19APR2016HiSeq_Run_Sample_ATE_51_UNCC_Gibas_TTAGGCAT_L006_R2_001-sampled.fastq --bowtie2out /Users/chadstachowicz/Downloads/meta/ATE_51.bz2 --nproc 4
#SampleID	Metaphlan_Analysis
#clade_name	NCBI_tax_id	relative_abundance	additional_species
k__Bacteria	2	100.0	
k__Bacteria|p__Actinobacteria	2|201174	61.04149	
k__Bacteria|p__Proteobacteria	2|1224	24.83551	
k__Bacteria|p__Firmicutes	2|1239	10.3088

**Comment by zz123-hub** [comment]
hello, I have the same problem. Have you solved it? I look forward to your recovery.
