### ISSUE TITLE
nreads of bowtie2 file

### ISSUE THREAD

**Issue by songdq** [biobakery/MetaPhlAn#205]
What is the meaning of ‘#nreads’ and ‘#avg_read_length’ at the end of the bowtie2 file？But “#nreads” is not the number of reads of the input file.  For example:

+ version:3.1.0
```
B1_2_8078375__2.8078373 363265__G6AXV1__HMPREF0673_01458
#nreads 15972026
#avg_read_length        148.32879642194422
```

**Comment by XiaomengWang0413** [comment]
Too many unknown species appear in my annotation results. What's going on? k__Bacteria|p__Proteobacteria|c__CFGB32252

k__Bacteria|p__Bacteroidetes|c__CFGB10780

**Comment by XiaomengWang0413** [comment]
@fbeghini
