### ISSUE TITLE
identify marker genes in order to customize the database

### ISSUE THREAD

**Issue by fbeghini** [biobakery/MetaPhlAn#23]
**[Original report](https://bitbucket.org/biobakery/metaphlan2/issue/23) by Eddi Lin (Bitbucket: [huadajie1046](https://bitbucket.org/huadajie1046), ).**

----------------------------------------

Hi Metaphlan2 community,

I am trying to include some newly discovered species into the marker database. After reading your instructions, I noticed that your procedure assume that I already know where the marker is. But I couldn't know that. Those samples are from metagenomic assembly. We know it is a new species because they have special SPNs.

Do you have any clue on how to identify marker gene fragments?

Thanks,

Eddi

**Comment by tenlives** [comment]
hi,
   did you get the answer ?

**Comment by fbeghini** [comment]
Hi @tenlives, marker usually are genes that are core genes for the species and unique for the species (no other species should have the same gene)

**Comment by tenlives** [comment]
> Hi @tenlives, marker usually are genes that are core genes for the species and unique for the species (no other species should have the same gene)

Thank you for replying， could you provide me the program code on idenfication of the maker genes, I dont find it , Thank you very much! I want to add the new maker gene to customize the maker genes database. Thank you very much!

**Comment by fbeghini** [comment]
You can find some parts of the pipeline here
https://github.com/SegataLab/pyphlan in the files named choco_, the entire
pipeline is not available here. You can identify new markers by using
VSEARCH to cluster all the CDS' of the species, identify the core clusters,
and map the centroids with bowie2 against all the bacterial-archaeal
reference genomes in GenBank. The centroids that map only to the species of
interest are your markers. If you have few genes unique to the species, you
can relax the search and include also genes that are present in very few
other species: keep in mind that the species that share the marker should
be listed in the 'ext' section of the marker.


----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

ᐧ
