### ISSUE TITLE
singularity use

### ISSUE THREAD

**Issue by fbeghini** [biobakery/MetaPhlAn#63]
**[Original report](https://bitbucket.org/biobakery/metaphlan2/issue/63) by LucCornet (Bitbucket: [Lcornet](https://bitbucket.org/Lcornet), GitHub: [Lcornet](https://github.com/Lcornet)).**

----------------------------------------

Dear [MetaPhlAn2](/biobakery/metaphlan2) team,

When running [MetaPhlAn2](/biobakery/metaphlan2) from singularity \(not build from docker\) is have the following issue : 

singularity exec ../MetaPhlAn2.simg [metaphlan2.py](http://metaphlan2.py) P1033.fastq --input\_type fastq --mpa\_pkl /scratch/ulg/medgen/lcornet/lichen/metaphlanDB/mpa\_v20\_m200.pkl --bowtie2db /scratch/ulg/medgen/lcornet/lichen/metaphlanDB/mpa\_v20\_m200 --nproc 1 > profiled.txt

Downloading MetaPhlAn2 database  
Please note due to the size this might take a few minutes  
ERROR: Unable to create folder for database install: ../metaphlanDB/mpa\_v20\_m200

I am not able to run [MetaPhlAn2](/biobakery/metaphlan2) without creating the DB, which is not possible in the container. I download the DB and build it with bowtie bot still not possible to run

Can you help me ?

‌

Luc

‌

‌

**Comment by SaimMomin12** [comment]
@fbeghini  Could you please tell, how this issue was solved? I am facing same issues with singularity
