### ISSUE TITLE
Download links

### ISSUE THREAD

**Issue by alienzj** [biobakery/MetaPhlAn#71]
https://github.com/biobakery/MetaPhlAn/blob/3.0/metaphlan/metaphlan.py#L42

Hi, Can you provide a ftp-like download address?

**Comment by fbeghini** [comment]
Hi, unfortunately, no. Do you have issues in downloading the database?

**Comment by alienzj** [comment]
Hi, we live inside a GFW, we cannot use the dropbox service on a computing cluster.

**Comment by fbeghini** [comment]
Were you able to download it from BitBucket?

**Comment by alienzj** [comment]
Hi,  we can download it from BitBucket.

**Comment by fbeghini** [comment]
Okay, I've uploaded the latest version `mpa_v30_CHOCOPhlAn_201901.md5` in the BitBucket Download section (https://bitbucket.org/biobakery/metaphlan2/downloads/)

**Comment by alienzj** [comment]
Thanks very much!
