### ISSUE TITLE
help message still uses "metaphlan.py"

### ISSUE THREAD

**Issue by kescobo** [biobakery/MetaPhlAn#73]
When installing v3 via conda, the script call is just `metaphlan` as opposed to `metaphlan.py`. I think this is definitely preferable, but all of the examples in the `--help` text reference `metaphlan.py`, which doesn't work (command not found)

**Comment by fbeghini** [comment]
Hi Kevin, 
I've updated the whole package and I'm waiting to push the latest edits to Bioconda in order to have an updated and final release

**Comment by kescobo** [comment]
👍
