### ISSUE TITLE
how to calculate Chao 1 using the output of metaphlan

### ISSUE THREAD

**Issue by ZhangDengwei** [biobakery/MetaPhlAn#74]
Dear all,

I have profiled the microbial community using metaphlan v3, and the output was the relative abundance for each bacteria, that is, the proportion. Then I'd like to evaluate its richness with Chao 1, but the input for calculating Chao 1 must be integers. Besides, the formula for calculating chao 1 and shannon involved in OTU, so I'm not sure whether using relative abundance as input for chao 1 or shannon is right. If so, how can i calculate them using the relative abundance matrix? Thanks very much!

**Comment by kescobo** [comment]
Hi @ZhangDengwei - I'm not certain, but this might be a question better asked on the [biobakery forums](https://forum.biobakery.org/c/Microbial-community-profiling/)
