### ISSUE TITLE
Profile tsv format

### ISSUE THREAD

**Issue by kescobo** [biobakery/MetaPhlAn#80]
While csv/tsv are not really well-defined specs, there are a couple of things about the new profile output that are a bit challenging with a couple of parsers I've used.

1. Include a "comments" (or something) column header in line 4 after `relative_abundance`. Right now, there are only 3 valid columns there, so that line can't be parsed as a header if desired.
2. Include taxids for `_unclassified` clades. My preference would be to use the upstream ids, and then a trailing `|` or something. 
    For example, I have one row that's  
    ```
    ...|g__Ruminococcaceae_unclassified|s__Clostridium_leptum\t2|1239|186801|186802|541000||1535
    ```

    And another that's
    ```
    ...|g__Ruminococcaceae_unclassified\t
    ```
    with nothing in the taxid column (leading to a `missing` or `NA` when parsed). Could that be
    `2|1239|186801|186802|541000|` as the taxid instead?
3. Having hashes in the comments column (column 4) doesn't do much, since there's a tab before them, meaning that a column is added even if they're parsed as comments. I think better to keep the column, but maybe remove the hash?

**Comment by fbeghini** [comment]
Thank you for the suggestions Kevin, the latest commits include all these fixes
