### ISSUE TITLE
Failed to download the database

### ISSUE THREAD

**Issue by bitcometz** [biobakery/MetaPhlAn#82]
hello, I used conda install -c bioconda metaphlan2 and run:

metaphlan2.py --input_type fastq test.fq --nproc 8 > profiled_metagenome.txt

**Downloading https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_latest

Warning: Unable to download https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_latest
Traceback (most recent call last):**

Could you help with this problem ?

Thanks!!!!

**Comment by fbeghini** [comment]
Hi,
we are updating the bioconda package to reflect the changes made in the repository, the database is no more available on bitbucket since we migrated the repository to GitHub.

In the meantime, you can get the latest MetaPhlAn2 from the repository

**Comment by UriaMorP** [comment]
Hey @bitcometz 
I'm not sure if this is the same thing (you did not provide any stack trace, but see if this 
[quick fix](https://github.com/biobakery/MetaPhlAn/issues/83#issue-607758165) helps you get it up and running.
