### ISSUE TITLE
an extra "mpa_" prefix

### ISSUE THREAD

**Issue by UriaMorP** [biobakery/MetaPhlAn#83]
https://github.com/biobakery/MetaPhlAn/blob/6d36efc0272955c26cf4a56abdd6fe215c5dc464/metaphlan2.py#L745

Hey there,
Thanks for your great work!

I just installed the latest MetaPhlAn release (latest available in bioconda channel) experimenting.
The command `metaphlan --install` resulted in the following error:
```
Traceback (most recent call last):
  File "/home/labs/elinav/uria/.conda/envs/mg_pipeline/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/home/labs/elinav/uria/.conda/envs/mg_pipeline/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1187, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/home/labs/elinav/uria/.conda/envs/mg_pipeline/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 610, in check_and_install_database
    download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
  File "/home/labs/elinav/uria/.conda/envs/mg_pipeline/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 463, in download_unpack_tar
    url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
KeyError: 'mpa_mpa_v30_CHOCOPhlAn_201901.tar'
```   

And the first thing I noticed is the extra "mpa_" prefix in the name of the .tar file. 

I tried to remove the prefix (in code I pulled through `conda install`), for the attached line as well as the mdsum inspection line (2 lines below it).

For now it seems to work fine.

**Comment by fbeghini** [comment]
Hi, thanks!
Have you checked you have installed the latest build for the 3.0 version? 
It should be `3.0-4` or `3.0-3` according to the date of installation, you can check by running `conda list` in the activated environment.

This problem was present in the `3.0-2` build and resolved in the latest one. Check to have the channels used by Bioconda set up correctly (https://bioconda.github.io/user/install.html#set-up-channels) in the right order

**Comment by rainyrubyzhou** [comment]
This works for me too!
`conda list`  only shows that the version I've installed is 3.0, and conda update does not work.
So I modify several lines that concatenate a "mpa_" before filename by deleting them.
Now it works fine:)
![image](https://user-images.githubusercontent.com/23096585/81527924-1084d000-938e-11ea-9971-1d9b0bac259b.png)

**Comment by fbeghini** [comment]
Hi @rainyrubyzhou ,
for checking the build number, you have to look the column after the version number. The latest build available is `pyh5ca1d4c_4`

**Comment by rainyrubyzhou** [comment]
@fasnicar Thank you! I'll check:)
