### ISSUE TITLE
conda install of metaphlan2 2.7.8 fails

### ISSUE THREAD

**Issue by tamburinif** [biobakery/MetaPhlAn#84]
Conda install of metaphlan2 2.7.8 fails on linux due to the matplotlib dependency:

```
$ conda create -c bioconda -c conda-forge -n metaphlan2 metaphlan2=2.7.8
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

PackagesNotFoundError: The following packages are not available from current channels:

  - matplotlib=1.5.2

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by fbeghini** [comment]
Hi, it seems that the defaults channel is missing from conda, (
https://bioconda.github.io/user/install.html#set-up-channels).
Also, I'd advise you to install version 2.8 which includes the latest code
for the database download from the current location

----

Francesco Beghini

PhD Student


Lab. of Computational Metagenomics

Department of Cellular, Computational and Integrative Biology - CIBIO

University of Trento
Via Sommarive 9, 38123 Trento, Italy

Il Mer 29 Apr 2020, 21:11 Fiona Tamburini <notifications@github.com> ha
scritto:

**Comment by tamburinif** [comment]
Thanks for your quick reply! I should mention that this also fails with the same error with the command `conda create -c bioconda -c conda-forge -c defaults -n metaphlan2 metaphlan2=2.7.8` so I'm not sure it's a channel issue (I have defaults in my conda config).

Thanks for the suggestion - when I run `conda create -c bioconda -c conda-forge -c defaults -n metaphlan2 metaphlan2=2.8` the metaphlan version installed is 2.7.7, which doesn't seem correct.

```
metaphlan2.py --version
MetaPhlAn version 2.7.7 (31 May 2018)
```

This version fails to install the metaphlan databases: the link to Dropbox appears to be updated, but the install still fails with the following error:

```% metaphlan2.py --install

Downloading MetaPhlAn2 database
Please note due to the size this might take a few minutes

Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1

Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
Traceback (most recent call last):
  File "/gstore/scratch/u/tamburif/miniconda3_envs/metaphlan2/bin/metaphlan2.py", line 1574, in <module>
    metaphlan2()
  File "/gstore/scratch/u/tamburif/miniconda3_envs/metaphlan2/bin/metaphlan2.py", line 1367, in metaphlan2
    check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'])
  File "/gstore/scratch/u/tamburif/miniconda3_envs/metaphlan2/bin/metaphlan2.py", line 836, in check_and_install_database
    download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
  File "/gstore/scratch/u/tamburif/miniconda3_envs/metaphlan2/bin/metaphlan2.py", line 745, in download_unpack_tar
    url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
UnboundLocalError: local variable 'ls_f' referenced before assignment
```

Would the best workaround be to clone the current metaphlan2 repo instead?

**Comment by fbeghini** [comment]
>Thanks for the suggestion - when I run conda create -c bioconda -c conda-forge -c defaults -n metaphlan2 metaphlan2=2.8 the metaphlan version installed is 2.7.7, which doesn't seem correct.

I forgot to update the version string inside the script but the installed version is correct (2.8)

Are you running MetaPhlAn2 from a machine that blocks the traffic to Dropbox? I've tried installing it from scratch and initialize the database and it works.

**Comment by tamburinif** [comment]
Ah, I understand - thanks! It is possible that traffic to Dropbox is blocked on our cluster. From the most recent issue/comment here, it looks like you may provide an alternative download option on Google Drive? That would be very helpful. Thank you!

**Comment by fbeghini** [comment]
Hi Fiona,
I've mirrored the databases on Google Drive, you can manually download the `tar` and `md5` files for `mpa_v20_m200` from [here](https://drive.google.com/drive/folders/1_HaY16mT7mZ_Z8JtesH8zCfG9ikWcLXG?usp=sharing), extract the `tar` under `/gstore/scratch/u/tamburif/miniconda3_envs/metaphlan2/bin/metaphlan_databases` and build the bowtie2 indices by running `bowtie2build  mpa_v20_m200.fna mpa_v20_m200`.

**Comment by tamburinif** [comment]
Thank you so much for setting this up!! This worked and I'm now able to run metaphlan2!
