### ISSUE TITLE
The the input file "metaphlan/DEMO.sam" must be in "BZ2" format

### ISSUE THREAD

**Issue by fbeghini** [biobakery/MetaPhlAn#85]
https://github.com/biobakery/MetaPhlAn/blob/46ef712a590faca541e9fa293eda891216d39994/metaphlan/utils/sample2markers.py#L98

Why it has to be only in BZ2 format? Should I be able to provide also uncompressed SAM files?

**Comment by abmiguez** [comment]
The default input format is the compressed files in bz2 format. However, you can upload both uncompressed sam and bam input files by using the parameter "-f', '--input_format".
