### ISSUE TITLE
Unable to download the database

### ISSUE THREAD

**Issue by rainyrubyzhou** [biobakery/MetaPhlAn#89]
When I run **metaphlan2.py** for the first time, it failed with info:
**Unable to download https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_latest**
Also, wget fails to download from this link.
Is there any update of the link?
![image](https://user-images.githubusercontent.com/23096585/81528074-71140d00-938e-11ea-8746-f8e01b8cb9d4.png)

**Comment by fbeghini** [comment]
Hi, you should get the latest version (2.8) from the release page here on Github or clone the repository. You have installed an older version which still points to the URLs pre-migration.

**Comment by plmeta** [comment]
My version is > 2.8:
MetaPhlAn version 2.96.1 (02 Feb 2020)

But I still get the error message: Unable to download https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_latest

Could you help to check?

Thanks!

**Comment by fbeghini** [comment]
@plmeta From where have you retrieved the software?

**Comment by plmeta** [comment]
From conda install. This is the link:
https://bioconda.github.io/recipes/metaphlan2/README.html

**Comment by fbeghini** [comment]
You have installed  2.96.1. For installing MetaPhlAn2 2.8 you have to
specify the version number
`conda install metaphlan2=2.8`
----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

ᐧ

**Comment by plmeta** [comment]
Actually I did that, but after installing, it showed version 2.7.7.

Does metaphlan2.8 use python2 or python3? I feel it might the problem with python. Also, version 2.9.1 should inherit from 2.8, right? If the link to download mpa_latest is working in 2.8, shouldn't it work in 2.91 as well?

I also need to use metaphlan2 with humann2, I wonder if something is not compatible there?

//Peidi

**Comment by fbeghini** [comment]
It's 2.8 even `-v` says 2.7.7, the conda recipe has to be updated since I forgot to update the version.

MetaPhlAn2.8 uses Python2, if you install it in a clean environment, it'll install the latest python2. 2.9.1 is not compatible with humann2, the conda recipe is not updated anymore since it is an old alpha version.
