### ISSUE TITLE
strainphlan.py :: should use mpa_dir env var

### ISSUE THREAD

**Issue by EricDeveaud** [biobakery/MetaPhlAn#95]
Hello, 

strainphlan.py and utils/extract_markers.py should use `mpa_dir` env var in order to set DEFAULT_DATABASE location

something like that
```
MPADIR=os.environ.get('mpa_dir', None)
if MPADIR is None:
    error('mpa_dir env var must be set, abort', exit=True)
DEFAULT_DATABASE = os.path.join(MPADIR, "metaphlan_databases", "mpa_v30_CHOCOPhlAn_201901.pkl")
```

also using os.path.join(x,y,z) instead of os.path.join(x, 'y/z') will grant you portability 

same principles will apply to utils/extract_markers.py

this will allow someone to have database loacted where they want and have bioths scripts to normaly work

regards

Eric

**Comment by abmiguez** [comment]
Hi Eric,
The mpa_dir variable is not longer used in the MetaPhlAn package. The default MetaPhlAn database should be located in the databases directory MetaPhlAn creates on the conda installation folder. However, for using an alternative database, both strainphlan and extract_markers scripts allow to specify its path using the _-d_ / _--database_ parameter.

Best, 
Aitor
