### ISSUE TITLE
external dependencies :: muscle or mafft ?

### ISSUE THREAD

**Issue by EricDeveaud** [biobakery/MetaPhlAn#96]
Hello, 

metaphlan/strainphlan.py defines a configuration that uses mafft instead of muscle
```
def get_phylophlan_configuration(phylophlan_mode):
    configuration = dict()
    # blastn, tblastn, diamond
    configuration.update({'map':'blastn'})
    # muscle, mafft, opal, upp
    configuration.update({'aligner':'mafft'})
    # fasttree, raxml, iqtree, astral, astrid
    configuration.update({'tree1':'raxml'})
    configuration.update({'tree2':''})

    return configuration
```

should we use muscle or mafft ?

regards

Eric

**Comment by abmiguez** [comment]
Hi Eric,
By default, StrainPhlAn 3.0, as well as PhyloPhlAn 3.0, uses mafft for the global alignment. However, if you want to use muscle instead, you can call the script with the _--phylophlan_configuration_ parameter and provide a custom phylophlan configuration file. https://github.com/biobakery/phylophlan/wiki#configuration-file

**Comment by EricDeveaud** [comment]
I was asking because the conda recipe says

```
run:
    - python >=3
    - bowtie2 >=2.0.0
    - dendropy
    - numpy
    - cmseq
    - phylophlan
    - biom-format
    - matplotlib-base
    - biopython
    - pandas
    - scipy
    - requests
    - blast >=2.6.0
    - muscle >=3.8.1551
    - pysam
```
did not saw mafft, instead muscle is mentioned, that why I was aking. 

so you confirm that metphlan depends on mafft 

regards

Eric

**Comment by abmiguez** [comment]
Hi Eric,
You are right, in the MetaPhlAn package mafft installation is not specified, however, as PhyloPhlAn is also installed in the package, you will get all the dependencies you need:

> run:
    - python >=3.7
    - biopython >=1.73
    - dendropy >=4.4.0
    - matplotlib-base >=3.1.0
    - numpy >=1.15.4
    - pandas >=0.24.2
    - seaborn >=0.9.0
    - blast >=2.6.0
    - diamond >=0.9
    - trimal >=1.4.1
    - muscle >=3.8.1551
    - mafft >=7.310
    - fasttree >=2.1.8
    - raxml >=8.2.10
    - iqtree >=1.6.6

**Comment by EricDeveaud** [comment]
thank's

I will then set mafft sa a dependency for metaphlan 

regards
