### ISSUE TITLE
tag phylophlan version to use in setup.py

### ISSUE THREAD

**Issue by EricDeveaud** [biobakery/MetaPhlAn#97]
Hello, 

in order to be consisitent and reproductible, please tag version of phylophlan to 'pip install' instead of dev whhich is by defition moving

```
install_requires = [ SNIP ... 'phylophlan @ git+https://github.com/biobakery/phylophlan@dev'],
                                                                       ^^^^^^^^^^^^^^^^^^
```

you may want to consider tha some people want to be abble to install and reinstall the exact same version of a tool alon the time, in order to rerun analysis iin the exact same conditions.

regards

Eric

**Comment by fbeghini** [comment]
Hi Eric,
in the latest version, the setup.py installs PhyloPhlAn from PyPi and not anymore from the repo dev branch (which is no longer present)

**Comment by EricDeveaud** [comment]
we usualy install package on our cluster from tagged release not from git tree
so does package manager.
we need to be abble to rebuild in a consistent maner the software we propose to our users. 
same version, same dependencies version and so on. 

above snippet was taken from setup.py from archive https://github.com/biobakery/MetaPhlAn/archive/3.0.tar.gz

so yes PhyloPhlAn is installed from @dev branch given your setup.py. 
NB I hacked it this way for our installation

`'phylophlan @ git+https://github.com/biobakery/phylophlan@3.0'` ;-)

regards

Eric

**Comment by fbeghini** [comment]
Yes, you're right, I was not checking the tagged version. I'll update and bump for a new release in few weeks

**Comment by EricDeveaud** [comment]
thanks
