### ISSUE TITLE
merge_metaphlan_tables.py: UnboundLocalError: local variable 'names' referenced before assignment 

### ISSUE THREAD

**Issue by JustinGibbons** [biobakery/MetaPhlAn#98]
I'm attempting to run merge_metaphlan_tables.py and I am receiving the following error:

```
Traceback (most recent call last):
  File "/shares/omicshub/apps/anaconda3/envs/metaphlan3/bin/merge_metaphlan_tables.py", line 10, in <module>
    sys.exit(main())
  File "/shares/omicshub/apps/anaconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/utils/merge_metaphlan_tables.py", line 78, in main
    merge(args.aistms, sys.stdout)
  File "/shares/omicshub/apps/anaconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/utils/merge_metaphlan_tables.py", line 46, in merge
    names = names,
UnboundLocalError: local variable 'names' referenced before assignment
```

I examined the source code and the variable "names" is not created when the header is 3 lines long.  This is what the header looks like in the files I am trying to merge:

```
#mpa_v30_CHOCOPhlAn_201901
#/shares/omicshub/apps/anaconda3/envs/metaphlan3/bin/metaphlan /work/j/jgibbons1/Preterm_MetaGenomes/Filtered_Random_Sample/SRR9865416_1_kneaddata.fastq --input_type fastq --bowtie2db /work/j/jgibbons1/Metaphlan_Database -t rel_ab --sample_id_key SRR9865416_1_kneaddata -o SRR9865416_1_kneaddata_metaphlan.tsv --nproc 3
#clade_name	NCBI_tax_id	relative_abundance	additional_species
```

**Comment by fbeghini** [comment]
Have you pasted all the header lines? It seems that is missing one line including the sample key 
`SRR9865416_1_kneaddata    Metaphlan_Analysis`

This line is always printed in the MetaPhlAn output profile

**Comment by JustinGibbons** [comment]
MetaPhlAn is definitely only  writing out 3 header lines. 

```
grep -c "#" SRR9865416_1_kneaddata_metaphlan.tsv
3
```

This is the MetaPhlAn 3.0 command I used:

```
metaphlan ${FASTQ_ARRAY[$SLURM_ARRAY_TASK_ID]} --input_type fastq --bowtie2db $NUC_DATABASE -t rel_ab --sample_id_key ${SAMPLE_ID_KEYS_ARRAY[$SLURM_ARRAY_TASK_ID]} -o ${OUTFILE_ARRAY[$SLURM_ARRAY_TASK_ID]} --nproc 3
```

**Comment by fbeghini** [comment]
Yes, you're right, there was missing a hash symbol in the third header line, 5fb4624512bda517f4cb36f2c39d8e128d58ffd1 fixes the output file.

In the meantime you can easily add the missing hash with something like this in awk
`awk '{if (NR==3) print "#"$0; else print $0;}' SRR9865416_1_kneaddata_metaphlan.tsv`
